
Nature:
  - nature
  - landscape
  - forest
  - mountain

Animes:
  - anime
  - manga
  - otaku

Cinema:
  - movie
  - film
  - cinema

BMX:
  - bmx
  - race
  - freestyle

Post-Apocalyptic:
  - apocalypse
  - wasteland
  - ruins

Utopia:
  - utopia
  - futuristic
  - future

Planet:
  - planet
  - galaxy
  - universe
  - space

